### ISSUE TITLE
Decide /signup secrecy policy

### ISSUE THREAD

**Issue by veganstraightedge** [secretlyus/secretlyus#6]
Right now the signup links on the site include the `?code=secret` in the URL. Which allows anyone who clicks the link to signup.

If you want to keep it truly invite only, I can remove that `?code=secret` from the URL so that randos can't signup. Only people that you give the secret URL to could.

(Currently there is no limit to the number of people in a group. That was never specced out in your business rules.)

**Comment by seanpecknold** [comment]
Yeah let's keep it truly invite only, that's perfect!
